// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADj9DPtzkNUYc12ogljlpEaJb0w182hTM',
    appId: '1:592106211553:web:4d8ed2238d5fbc821c4fa0',
    messagingSenderId: '592106211553',
    projectId: 'talikhata-clone',
    authDomain: 'talikhata-clone.firebaseapp.com',
    storageBucket: 'talikhata-clone.firebasestorage.app',
    measurementId: 'G-E72LPQ8Q0W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY7Jd61qtQ-UeaWfow0oGOmHuTNnnj6VQ',
    appId: '1:592106211553:android:2e7352293ebd65241c4fa0',
    messagingSenderId: '592106211553',
    projectId: 'talikhata-clone',
    storageBucket: 'talikhata-clone.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoDK2hJeuJhfD7XJ-MlU5-bQffkwmtHaI',
    appId: '1:592106211553:ios:f08df8061ea4e7e31c4fa0',
    messagingSenderId: '592106211553',
    projectId: 'talikhata-clone',
    storageBucket: 'talikhata-clone.firebasestorage.app',
    iosBundleId: 'com.example.talikhatClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoDK2hJeuJhfD7XJ-MlU5-bQffkwmtHaI',
    appId: '1:592106211553:ios:f08df8061ea4e7e31c4fa0',
    messagingSenderId: '592106211553',
    projectId: 'talikhata-clone',
    storageBucket: 'talikhata-clone.firebasestorage.app',
    iosBundleId: 'com.example.talikhatClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADj9DPtzkNUYc12ogljlpEaJb0w182hTM',
    appId: '1:592106211553:web:16e8587a3da554f41c4fa0',
    messagingSenderId: '592106211553',
    projectId: 'talikhata-clone',
    authDomain: 'talikhata-clone.firebaseapp.com',
    storageBucket: 'talikhata-clone.firebasestorage.app',
    measurementId: 'G-Z5M3JR3WWZ',
  );
}
